docker: False
filter: False
detect_threshold: 5.5 # phase 1
detect_channel_radius: 100 # phase 1
detect_time_radius_msec: 1.5 # phase 1
scheme2_phase2_detect_threshold: 5.5
scheme2_phase2_detect_channel_radius: 80
scheme2_phase2_detect_time_radius_msec: 0.5
npca_per_subdivision: 10
scheme2_training_duration_sec: 400